name: Elixir CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-latest:
    name: Test (v1.18.4, OTP-28)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.4'
          otp-version: '28.0'

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test

  test-oldest:
    name: Test (v1.7.0, OTP-21)
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.7.0'
          otp-version: '21.0'

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test
