name: Elixir CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test (Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.18.4'
            otp: '28.0'
            os: ubuntu-latest
          - elixir: '1.7.0'
            otp: '22.0'
            os: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          version-type: 'strict'

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test
