name: Elixir CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.7.0'
            otp: '21.0'

          - elixir: '1.18.4'
            otp: '28.0'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test
